Unpin ecdsa
mpdavis/python-jose pull request #192
Opened 2020-10-22 07:54 UTC by przemyslaw-jakielaszek

There is a newer version of ecdsa `0.16.0`. We can unpin version, because all of tests passed.

2020-10-30 10:37 UTC, m-aciek commented
Hi @blag, could you review and merge the change? It looks like new version of ecdsa gives some performance boost.

2020-11-18 14:06 UTC, Colin-b commented
Hello maintainers, can you have a look at this? the new pip resolver will prevent usage of ecdsa 0.16 even if it can be used with python-jose.

2020-11-19 23:50 UTC, blag commented
NAK. Just because the most recent version of ecdsa works for us doesn't mean that 0.15 won't mess things up somehow. We still need to blacklist ecdsa 0.15: `ecdsa != 0.15`.

2020-11-19 23:50 UTC, blag requested changes

2020-11-19 23:50 UTC, blag commented on requirements.txt
> +ecdsa
```suggestion
ecdsa != 0.15
```

2020-11-23 21:02 UTC, blag approved these changes

2020-11-23 21:04 UTC, merged

2020-11-23 21:04 UTC, blag commented
Thanks!